# Generated by Django 2.2.1 on 2021-07-19 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20210719_0741'),
    ]

    operations = [
        migrations.AddField(
            model_name='ratingofbook',
            name='ratingValue',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
