# Generated by Django 3.2.5 on 2021-07-24 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20210724_1422'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='number',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
