# Generated by Django 2.2.1 on 2021-07-21 10:24

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0003_auto_20210720_1844'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserRating',
            new_name='BookRating',
        ),
    ]
