# Generated by Django 2.2.1 on 2021-07-16 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20210716_0944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='ratings',
            field=models.TextField(default=''),
        ),
    ]
