# Generated by Django 3.2.5 on 2021-07-24 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_book_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='number',
            new_name='num_avail',
        ),
    ]
