# Generated by Django 2.2.1 on 2021-07-23 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_auto_20210721_2229'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookrating',
            name='desc',
            field=models.TextField(null=True),
        ),
    ]
