# Generated by Django 2.2.1 on 2021-07-22 07:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_bookrating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookrating',
            name='rater',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
