# Generated by Django 2.2.1 on 2021-07-21 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_auto_20210721_2101'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='total_rated',
            field=models.IntegerField(default=0),
        ),
    ]
