# Generated by Django 2.2.1 on 2021-07-16 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_auto_20210716_0948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='ratings',
            field=models.TextField(blank=True),
        ),
    ]
