# Generated by Django 2.2.1 on 2021-07-18 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_bookrating'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookrating',
            name='rating',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='bookrating',
            name='rated',
            field=models.BooleanField(default=False),
        ),
    ]
