# Generated by Django 2.2.1 on 2021-07-21 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_book_total_rated'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookrate',
            old_name='bookname',
            new_name='book',
        ),
    ]
