# Generated by Django 2.2.1 on 2021-07-16 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_auto_20210716_1031'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='ctrating',
            field=models.IntegerField(default=0),
        ),
    ]
